import React from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Button } from '@chakra-ui/react'
import Link from 'next/link'
import HomeCompIndex from '../components/home/ui'

export default function Home(){
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HomeCompIndex />
      </main>
    </div>
  )
}
